import { equipmentSynopsis } from '../model/EquipmentSynopsis'

// 商城页面
// 首选办公
export const OfficePreferredArr: equipmentSynopsis[] = [
  new equipmentSynopsis($rawfile('Mall/ThinkPad_E14.jpg'), 'ThinkPad_E14', 'i3-11/8G/256G/核显/14', 108),
  new equipmentSynopsis($rawfile('Mall/Link.jpg'), 'Link-R S2000', 'i9-14/32G/2048G/独显/27', 648),
  new equipmentSynopsis($rawfile('Mall/HP_440G7.jpg'), '惠普 440G7', 'i5-10/8G/256G/核显/14', 118),
  new equipmentSynopsis($rawfile('Mall/DE_CM3980.jpg'), '戴尔 成铭3980', 'i3-8/8G/256G/核显/21.4', 95),
  new equipmentSynopsis($rawfile('Mall/ThinkPad_E480.jpg'), 'ThinkPad_E480', 'i3-7/8G/256G/核显/14', 80),
  new equipmentSynopsis($rawfile('Mall/ThinkPad_E14Gen1.jpg'), 'ThinkPad_E14Gen1', 'i3-10/8G/256G/核显/14', 103)
]

// 便携办公
export const OfficePortableArr: equipmentSynopsis[] = [
  new equipmentSynopsis($rawfile('Mall/HP_440G7.jpg'), '惠普 430G8', 'i5-11/8G/256G/核显/13.3', 128),
  new equipmentSynopsis($rawfile('Mall/DE_CM3980.jpg'), 'ThinkPad X390', 'i5-10/8G/256G/核显/13.3', 123),
  new equipmentSynopsis($rawfile('Mall/ThinkPad_X13.jpg'), 'ThinkPad X13', 'i5-10/8G/256G/核显/13.3', 128),
  new equipmentSynopsis($rawfile('Mall/ThinkPad_X13.jpg'), 'ThinkPad X13', 'i5-10/8G/256G/核显/13.3', 153)
]

// 技术开发
export const OfficeTechnologyArr: equipmentSynopsis[] = [
  new equipmentSynopsis($rawfile('Mall/HP_400G9_SFFR.jpg'), '惠普 H400G9 SFF R', 'i5-13/16G/512G/核显/23.8', 158),
  new equipmentSynopsis($rawfile('Mall/ThinkPad_E141.jpg'), 'ThinkPad E14', 'i5-13/8G/512G/核显/14', 208),
  new equipmentSynopsis($rawfile('Mall/ThinkPad_E14_Gen4.jpg'), 'ThinkPad E14 Gen4', 'i5-12/16G/256G * 2/核显/14', 178),
  new equipmentSynopsis($rawfile('Mall/HP_288G9.jpg'), '惠普 288G9', 'i5-12/8G/256G/核显/21.5', 128)
]

// 图形处理
export const OfficeGraphicsArr: equipmentSynopsis[] = [
  new equipmentSynopsis($rawfile('Mall/ThinkPad_E14_Gen5.jpg'), 'ThinkPad E14 Gen5', 'i7-13/16/512G/核显/14', 256),
  new equipmentSynopsis($rawfile('Mall/ThinkPad_P16V.jpg'), 'ThinkPad P16V', 'i7-13/16G/512G/4G独显/16', 458),
  new equipmentSynopsis($rawfile('Mall/HP_288G9TX.jpg'), '惠普 88G9TX', 'i5-12/16G/1T+256G/4G独显/24', 208),
  new equipmentSynopsis($rawfile('Mall/HP_Z2_G9_Gen2.jpg'), '惠普 Z2 G9 Gen2', 'i7-13700K/32G/1T SSD/RTX 4070/27', 518)
]



// 分类页面
// 综合推荐
export const synthesisRecommend: equipmentSynopsis[] = [
  new equipmentSynopsis($rawfile('Classify/synthesisRecommend/FLP_Philips_203V5LSB2_20.jpg'), '飞利浦Philips 203V5LSB2 20英寸显示器租赁', '20/1600X900/60HZ/VGA', 20),
  new equipmentSynopsis($rawfile('Classify/synthesisRecommend/DE_Dell_E2016H_21.jpg'), '戴尔Dell E2220H 21.5英寸显示器租赁', '21.5/1920X1080/60HZ/VGA+DP', 25),
  new equipmentSynopsis($rawfile('Classify/synthesisRecommend/DE_Dell_E2016H_20.jpg'), '戴尔Dell E2016H 20英寸显示器租赁', '19.5/1600X900/60HZ/VGA+DP', 20),
  new equipmentSynopsis($rawfile('Classify/synthesisRecommend/HP_M2456_23.8.jpg'), '惠普HP M2456 23.8英寸显示器 HDMI/VGA/DP', '23.8/1920X1080/60HZ/HDMI+VGA+DP',33),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E490/ThinkPad_E490_Swiper1.jpg'), 'ThinkPad E14 E490 14英寸笔记本电脑', 'i3-8145U/8G/256G SSD/核显/14/HD', 65),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E14_Gen1/ThinkPad_E14_Gen1_Swiper1.jpg'), 'ThinkPad E14 Gen1 14英寸笔记本电脑', 'i3-10110U/8G/256G SSD/核显/14/FHD', 78),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E480/ThinkPad_E480_Swiper1.jpg'), 'ThinkPad E480 14英寸笔记本电脑', 'i3-7020U/8G/256G SSD/核显/14/HD', 80),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E14_Gen2/ThinkPad_E14_Gen2_Swiper1.jpg'), 'ThinkPad E14 Gen2 14英寸笔记本电脑', 'i3-1115G4/8G/256G SSD/核显/14/FHD', 88),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E480/ThinkPad_E480_Swiper1.jpg'), 'ThinkPad E480 14英寸笔记本电脑', 'i3-8130U/8G/256G SSD/核显/14/HD\n基础办公/接口齐全/耳机接口/高端品牌/高端定性/内置摄像头', 93),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E490/ThinkPad_E490_Swiper1.jpg'), 'ThinkPad E14 E490 14英寸笔记本电脑', 'i3-8145U/8G/256G SSD/核显/14/HD', 93),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_L14/ThinkPad_L14_Swiper1.jpg'), '[新客特价]ThinkPad L14 14英寸笔记本电脑', 'i5-10210U/16G/256G SSD/R625 2G独显/14/FHD', 95),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/Dell/Dell_5400/ProductDetails1.jpg'), '戴尔Dell 5400 笔记本电脑租赁', 'i5-8365UU/8G/256G SSD/核显/14/FHD', 98),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_X390/ThinkPad_X390_Swiper1.jpg'), 'ThinkPad X390 13.3英寸笔记本电脑', 'i5-10210U/8G/256G SSD/核显/13.3/HD', 98),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_X390/ThinkPad_X390_Swiper1.jpg'), 'ThinkPad X390 13.3英寸笔记本电脑租赁', 'i5-10210U/8G/256G SSD/核显/13.3/HD', 98),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E96XT/Lenove_E96XT_Swiper1.jpg'), '联想Lenovo E96X 台式机电脑租赁', 'G4900/8G/256G SSD/核显/联想T2055 20英寸显示器', 73),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E96XT/Lenove_E96XT_Swiper2.png'), '联想Lenovo E96X 台式机电脑租赁', 'G4900/8G/256G SSD/核显/惠普M2256 21.5英寸显示器', 78),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E98T/Lenove_E98T_Swiper1.jpg'), '联想Lenovo E98 台式机电脑租赁', 'G5905/8G/256G SSD/核显/联想T2055 20英寸显示器', 83),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E97T/Lenove_E97T_Swiper1.png'), '联想Lenovo E97 台式机电脑租赁', 'G5905/8G/256G SSD/核显/飞利浦203V5LSB2 20英寸显示器', 83),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E97T/Lenove_E97T_Swiper1.png'), '联想Lenovo E97 台式机电脑租赁', 'G5905/8G/256G SSD/核显/飞利浦223V5LSB 21.5英寸显示器', 88),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E98T/Lenove_E98T_Swiper1.jpg'), '联想Lenovo E98 台式机电脑租赁', 'G5905/8G/256G SSD/核显/惠普M22255 21.5英寸显示器', 88),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E98T/Lenove_E98T_Swiper1.jpg'), '联想Lenovo E98 台式机电脑租赁', 'G5905/8G/256G SSD/核显/联想P241  23.8英寸显示器', 103),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E96XD/Lenove_E96XD_Swiper1.png'), '联想Lenovo E98X 单主机电脑租赁', 'G4900/8G/256G SSD/核显\n/基础办公/接口齐全/耳机接口/高稳定性', 63),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E97D/Lenove_E97D_Swiper1.png'), '联想Lenovo E97 单主机电脑租赁', 'G5905/8G/256G SSD/核显\n/基础办公/高端品牌/耳机接口/高稳定性', 73),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_X13/ThinkPad_X13_Swiper1.jpg'), 'ThinkPad X13 13.3英寸笔记本电脑租赁', 'i5-10210U/8G/256G SSD/核显/13.3/HD', 98),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_T14/ThinkPad_T14_Swiper1.jpg'), '[新客特价]ThinkPad T14 14英寸笔记本电脑租赁', 'i5-10210U/16G/256G SSD/核显/14/HD', 99),
  new equipmentSynopsis($rawfile('Classify/synthesisRecommend/FLP_Philips_203V5LSB2_21.jpg'), '飞利浦Philips 223V5LSB 21.5英寸显示器租赁', '20/1920X1080/60HZ/VGA+DP', 25),
  new equipmentSynopsis($rawfile('Classify/synthesisRecommend/FLP_Philips_241V8_23.jpg'), '飞利浦Philips 241V8 23英寸显示器租赁', '23.8/1920X1080/75HZ/HDMI+VGA',33),
  new equipmentSynopsis($rawfile('Classify/synthesisRecommend/FLP_Philips_27B2N2100_27.jpg'), '飞利浦Philips 24B2N2100 27英寸显示器租赁', '27/1920X1080/100HZ/HDMI+VGA+DP',35),
  new equipmentSynopsis($rawfile('Classify/synthesisRecommend/FLP_Philips_241V8_23.jpg'), '飞利浦Philips 241V8 23.8英寸显示器租赁', '23.8/1920X1080/75HZ/HDMI+VGA',33),
]

// 笔记本分类
export const LaptopClassify: equipmentSynopsis[] = [
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E490/ThinkPad_E490_Swiper1.jpg'), 'ThinkPad E14 E490 14英寸笔记本电脑', 'i3-8145U/8G/256G SSD/核显/14/HD', 65),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E14_Gen1/ThinkPad_E14_Gen1_Swiper1.jpg'), 'ThinkPad E14 Gen1 14英寸笔记本电脑', 'i3-10110U/8G/256G SSD/核显/14/FHD', 78),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E480/ThinkPad_E480_Swiper1.jpg'), 'ThinkPad E480 14英寸笔记本电脑', 'i3-7020U/8G/256G SSD/核显/14/HD', 80),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E14_Gen2/ThinkPad_E14_Gen2_Swiper1.jpg'), 'ThinkPad E14 Gen2 14英寸笔记本电脑', 'i3-1115G4/8G/256G SSD/核显/14/FHD', 88),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E480/ThinkPad_E480_Swiper1.jpg'), 'ThinkPad E480 14英寸笔记本电脑', 'i3-8130U/8G/256G SSD/核显/14/HD\n基础办公/接口齐全/耳机接口/高端品牌/高端定性/内置摄像头', 93),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E490/ThinkPad_E490_Swiper1.jpg'), 'ThinkPad E14 E490 14英寸笔记本电脑', 'i3-8145U/8G/256G SSD/核显/14/HD', 93),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_L14/ThinkPad_L14_Swiper1.jpg'), '[新客特价]ThinkPad L14 14英寸笔记本电脑', 'i5-10210U/16G/256G SSD/R625 2G独显/14/FHD', 95),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/Dell/Dell_5400/ProductDetails1.jpg'), '戴尔Dell 5400 笔记本电脑租赁', 'i5-8365UU/8G/256G SSD/核显/14/FHD', 98),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_X390/ThinkPad_X390_Swiper1.jpg'), 'ThinkPad X390 13.3英寸笔记本电脑', 'i5-10210U/8G/256G SSD/核显/13.3/HD', 98),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_X390/ThinkPad_X390_Swiper1.jpg'), 'ThinkPad X390 13.3英寸笔记本电脑租赁', 'i5-10210U/8G/256G SSD/核显/13.3/HD', 98),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_X13/ThinkPad_X13_Swiper1.jpg'), 'ThinkPad X13 13.3英寸笔记本电脑租赁', 'i5-10210U/8G/256G SSD/核显/13.3/HD', 98),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_T14/ThinkPad_T14_Swiper1.jpg'), '[新客特价]ThinkPad T14 14英寸笔记本电脑租赁', 'i5-10210U/16G/256G SSD/核显/14/HD', 99),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E14_Gen1/ThinkPad_E14_Gen1_Swiper1.jpg'), 'ThinkPad E14 Gen1 14英寸笔记本电脑租赁', 'i3-10110U/8G/256G SSD/核显/14/HD', 103),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E14_Gen2/ThinkPad_E14_Gen2_Swiper1.jpg'), 'ThinkPad E14 Gen2 14英寸笔记本电脑租赁', 'i3-1115G4/8/256G SSD/核显/14/FHD', 108),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/Lenovo/Lenovo_YTS14/Lenovo_YTS14_Swiper1.png'), 'Lenovo 扬天S14笔记本电脑租赁', 'i5-1115G7/8G/512G SSD/核显/14/FHD', 108),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_X390/ThinkPad_X390_Swiper1.jpg'), 'ThinkPad X390 13.3英寸笔记本电脑租赁', 'i5-8265U/8G/256G SSD/核显/13.3/HD', 113),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/HP/HP_440G8/HP_440G8_Swiper1.jpg'), '惠普HP 440G8 14英寸笔记本电脑租赁', 'i5-1135G7/16G/512G SSD/核显/14/FHD', 113),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/HP/HP_430G8/HP_430G8_Swiper1.jpg'), '惠普HP 430G8 13.3英寸笔记本电脑租赁', 'i5-10210U/16G/512G SSD/核显/13.3/FHD', 113),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E14_Gen1/ThinkPad_E14_Gen1_Swiper1.jpg'), 'ThinkPad E14 Gen1 14英寸笔记本电脑租赁', 'i5-10210U/16G/512G SSD/核显/14/FHD', 113),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/HP/HP_440G7/HP_440G7_Swiper1.jpg'), '惠普HP 440G7 14英寸笔记本电脑租赁', 'i5-10210U/8G/256G SSD/核显/14/FHD', 118),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E14_Gen2/ThinkPad_E14_Gen2_Swiper1.jpg'), 'ThinkPad E14 Gen2 14英寸笔记本电脑租赁', 'i3-1115G4/8G/512G SSD/核显/14/FHD', 118),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E14_Gen1/ThinkPad_E14_Gen1_Swiper1.jpg'), 'ThinkPad E14 Gen1 14英寸笔记本电脑租赁', 'i5-10210U/8G/256G SSD/核显/14/FHD', 123),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_X390/ThinkPad_X390_Swiper1.jpg'), 'ThinkPad X390 13.3英寸笔记本电脑租赁', 'i5-10210U/8G/256G SSD/核显/13.3/HD', 123),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E14_Gen2/ThinkPad_E14_Gen2_Swiper1.jpg'), 'ThinkPad E14 Gen2 14英寸笔记本电脑租赁', 'i5-1135G7/16G/512G SSD/核显/14/FHD', 123),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/HP/HP_440G8/HP_440G8_Swiper1.jpg'), '惠普HP 440G8 14英寸笔记本电脑租赁', 'i5-1135G7/8G/256G SSD/核显/14/FHD', 128),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/HP/HP_430G8/HP_430G8_Swiper1.jpg'), '惠普HP 430G8 13.3英寸笔记本电脑租赁', 'i5-1135G7/8G/256G SSD/核显/13.3/FHD', 128),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_X390/ThinkPad_X390_Swiper1.jpg'), 'ThinkPad X390 13.3英寸笔记本电脑租赁', 'i5-10210U/8G/256G SSD/核显/13.3/HD', 128),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/Lenovo/Lenovo_YTS14/Lenovo_YTS14_Swiper1.png'), 'Lenovo 扬天S14笔记本电脑租赁', 'i5-1115G7/16G/512G SSD/核显/14/FHD', 135),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/HP/HP_440G7/HP_440G7_Swiper1.jpg'), '惠普HP 440G7 14英寸笔记本电脑租赁', 'i5-10210U/16G/1T/256G SSD/核显/14/FHD', 138),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_T14/ThinkPad_T14_Swiper1.jpg'), '[新客特价]ThinkPad T14 14英寸笔记本电脑租赁', 'i5-10210U/16G/256G SSD/核显/14/FHD', 99),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/ThinkPad/ThinkPad_E14_Gen1/ThinkPad_E14_Gen1_Swiper1.jpg'), 'ThinkPad E14 Gen1 14英寸笔记本电脑租赁', 'i3-10110U/8G/256G SSD/核显/14/FHD', 103),
  new equipmentSynopsis($rawfile('ProductDetails/Laptop/Lenovo/Lenovo_YTS14/Lenovo_YTS14_Swiper1.png'), 'Lenovo 扬天S14笔记本电脑租赁', 'i5-1115G7/8G/512G SSD/核显/14/FHD', 108),
]

// 台式机分类
export const DesktopClassify: equipmentSynopsis[] = [
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E96XT/Lenove_E96XT_Swiper1.jpg'), '联想Lenovo E96X 台式机电脑租赁', 'G4900/8G/256G SSD/核显/联想T2055 20英寸显示器', 73),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E96XT/Lenove_E96XT_Swiper2.png'), '联想Lenovo E96X 台式机电脑租赁', 'G4900/8G/256G SSD/核显/惠普M2256 21.5英寸显示器', 78),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E98T/Lenove_E98T_Swiper1.jpg'), '联想Lenovo E98 台式机电脑租赁', 'G5905/8G/256G SSD/核显/联想T2055 20英寸显示器', 83),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E97T/Lenove_E97T_Swiper1.png'), '联想Lenovo E97 台式机电脑租赁', 'G5905/8G/256G SSD/核显/飞利浦203V5LSB2 20英寸显示器', 83),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E97T/Lenove_E97T_Swiper1.png'), '联想Lenovo E97 台式机电脑租赁', 'G5905/8G/256G SSD/核显/飞利浦223V5LSB 21.5英寸显示器', 88),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E98T/Lenove_E98T_Swiper1.jpg'), '联想Lenovo E98 台式机电脑租赁', 'G5905/8G/256G SSD/核显/惠普M22255 21.5英寸显示器', 88),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E98T/Lenove_E98T_Swiper1.jpg'), '联想Lenovo E98 台式机电脑租赁', 'G5905/8G/256G SSD/核显/联想P241  23.8英寸显示器', 103),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E96XD/Lenove_E96XD_Swiper1.png'), '联想Lenovo E98X 单主机电脑租赁', 'G4900/8G/256G SSD/核显\n/基础办公/接口齐全/耳机接口/高稳定性', 63),
  new equipmentSynopsis($rawfile('ProductDetails/Desktop/Lenove/Lenove_E97D/Lenove_E97D_Swiper1.png'), '联想Lenovo E97 单主机电脑租赁', 'G5905/8G/256G SSD/核显\n/基础办公/高端品牌/耳机接口/高稳定性', 73),
]





